baseURL = 'https://positopensource.netlify.app'
languageCode = 'en-us'
title = 'Posit Open Source'
theme = 'hugo-theme-tailwind'
ignoreFiles = ['\.qmd$', '\.ipynb$']

[params]
subtitle = ""

[taxonomies]
  tag = 'tags'
  category = 'categories'
  person = 'people'
  software = 'software'
  language = 'languages'
  event = 'events'
  resource = 'resources'

[markup]

[markup.highlight]
  lineNos = true
  noClasses = false

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'People'
    url = '/people/'
    weight = 2
  [[menu.main]]
    name = 'Software'
    url = '/packages/'
    weight = 3
  [[menu.main]]
    name = 'Events'
    url = '/events/'
    weight = 4
  [[menu.main]]
    name = 'Resources'
    url = '/resources/'
    weight = 5
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
