baseURL = 'https://positopensource.netlify.app'
languageCode = 'en-us'
title = 'Posit Open Source'
theme = 'hugo-theme-tailwind'
showAuthor = true
ignoreFiles = ['\.qmd$', '\.ipynb$']

[markup]
[markup.highlight]
  # lineNos = true
  noClasses = false
# Markup configuration
[markup.goldmark.renderer]
unsafe = true


# Main navigation menu
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'People'
    url = '/people/'
    weight = 2
  [[menu.main]]
    name = 'Packages'
    url = '/packages/'
    weight = 3
  [[menu.main]]
    name = 'Events'
    url = '/events/'
    weight = 4
  [[menu.main]]
    name = 'Resources'
    url = '/resources/'
    weight = 5
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
